from __future__ import annotations

from typing import Any


DEMO_SCENARIOS: list[dict[str, Any]] = [
    {
        "id": "invasive",
        "label": "Invasive risk",
        "tag": "Aedes albopictus · Spain",
        "description": "Fetches GBIF API records for an invasive species case when network mode is enabled. If GBIF is unavailable, old fixture records are not reused.",
        "form": {
            "taxon": "Aedes albopictus",
            "taxon_key": 1651430,
            "region_name": "Spain GBIF bbox",
            "bbox": [-10.0, 35.0, 4.5, 44.5],
            "purpose": "invasive_watch",
            "source_mode": "online_with_empty_fallback",
            "use_fixture": False,
            "max_records": 300,
        },
    },
    {
        "id": "gaps",
        "label": "Forest gaps",
        "tag": "Quercus robur · W Europe",
        "description": "Runs a GBIF API query for a common tree taxon and ranks survey-priority grid cells.",
        "form": {
            "taxon": "Quercus robur",
            "taxon_key": 2878688,
            "region_name": "Western Europe GBIF bbox",
            "bbox": [-10.0, 42.0, 12.0, 56.0],
            "purpose": "sampling_gaps",
            "source_mode": "online_with_empty_fallback",
            "use_fixture": False,
            "max_records": 300,
        },
    },
    {
        "id": "quality",
        "label": "Data review",
        "tag": "Lynx pardinus · Iberia",
        "description": "Uses GBIF API records to group quality issues by datasetKey for a Publisher Feedback Pack.",
        "form": {
            "taxon": "Lynx pardinus",
            "taxon_key": 2435261,
            "region_name": "Iberian Peninsula GBIF bbox",
            "bbox": [-10.0, 35.0, 4.5, 44.5],
            "purpose": "dataset_quality_review",
            "source_mode": "online_with_empty_fallback",
            "use_fixture": False,
            "max_records": 300,
        },
    },
    {
        "id": "offline",
        "label": "Offline sample",
        "tag": "stable regression data",
        "description": "Uses the deterministic offline fixture for no-network testing and regression checks.",
        "form": {
            "taxon": "Aedes albopictus",
            "taxon_key": 1651430,
            "region_name": "Spain offline fixture bbox",
            "bbox": [-10.0, 35.0, 4.5, 44.5],
            "purpose": "invasive_watch",
            "source_mode": "fixture",
            "use_fixture": True,
            "max_records": 300,
        },
    },
]


REGION_PRESETS: list[dict[str, Any]] = [
    {
        "id": "spain",
        "label": "Spain",
        "region_name": "Spain GBIF bbox",
        "bbox": [-10.0, 35.0, 4.5, 44.5],
        "description": "Compact judge demo extent with strong GBIF occurrence coverage.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "ES",
        "featured": True,
    },
    {
        "id": "iberian",
        "label": "Iberian Peninsula",
        "region_name": "Iberian Peninsula GBIF bbox",
        "bbox": [-10.0, 35.0, 4.5, 44.5],
        "description": "Useful for Iberian conservation and dataset quality tests.",
        "type": "research_region",
        "group": "Research regions",
        "featured": True,
    },
    {
        "id": "western-europe",
        "label": "Western Europe",
        "region_name": "Western Europe GBIF bbox",
        "bbox": [-10.0, 42.0, 12.0, 56.0],
        "description": "Broader tree, plant and bird sampling-gap experiments.",
        "type": "research_region",
        "group": "Research regions",
        "featured": True,
    },
    {
        "id": "mediterranean",
        "label": "Western Mediterranean",
        "region_name": "Western Mediterranean live bbox",
        "bbox": [-6.5, 34.5, 16.0, 46.5],
        "description": "Coastal and island corridor tests for invasive-watch workflows.",
        "type": "research_region",
        "group": "Research regions",
        "featured": True,
    },
    {
        "id": "north-america",
        "label": "North America",
        "region_name": "North America test bbox",
        "bbox": [-130.0, 24.0, -60.0, 55.0],
        "description": "Large-area smoke test; keep max records moderate for responsive demos.",
        "type": "research_region",
        "group": "Research regions",
        "featured": False,
    },
    {
        "id": "portugal",
        "label": "Portugal",
        "region_name": "Portugal GBIF bbox",
        "bbox": [-9.6, 36.8, -6.0, 42.2],
        "description": "Country bbox for Iberian biodiversity checks.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "PT",
        "featured": True,
    },
    {
        "id": "france",
        "label": "France",
        "region_name": "France GBIF bbox",
        "bbox": [-5.2, 41.3, 9.7, 51.2],
        "description": "Country bbox for Western Europe workflows.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "FR",
        "featured": True,
    },
    {
        "id": "italy",
        "label": "Italy",
        "region_name": "Italy GBIF bbox",
        "bbox": [6.6, 36.4, 18.8, 47.1],
        "description": "Country bbox for Mediterranean species checks.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "IT",
        "featured": True,
    },
    {
        "id": "germany",
        "label": "Germany",
        "region_name": "Germany GBIF bbox",
        "bbox": [5.8, 47.2, 15.1, 55.1],
        "description": "Country bbox for Central Europe records.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "DE",
        "featured": False,
    },
    {
        "id": "united-kingdom",
        "label": "United Kingdom",
        "region_name": "United Kingdom GBIF bbox",
        "bbox": [-8.7, 49.8, 1.9, 60.9],
        "description": "Country bbox for UK occurrence checks.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "GB",
        "featured": False,
    },
    {
        "id": "norway",
        "label": "Norway",
        "region_name": "Norway GBIF bbox",
        "bbox": [4.5, 57.8, 31.2, 71.4],
        "description": "Northern Europe bbox for climate and range-shift checks.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "NO",
        "featured": False,
    },
    {
        "id": "sweden",
        "label": "Sweden",
        "region_name": "Sweden GBIF bbox",
        "bbox": [10.6, 55.0, 24.2, 69.2],
        "description": "Scandinavian country bbox for forest and species workflows.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "SE",
        "featured": False,
    },
    {
        "id": "poland",
        "label": "Poland",
        "region_name": "Poland GBIF bbox",
        "bbox": [14.1, 49.0, 24.2, 54.9],
        "description": "Central/Eastern Europe country bbox.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "PL",
        "featured": False,
    },
    {
        "id": "turkiye",
        "label": "Turkiye",
        "region_name": "Turkiye GBIF bbox",
        "bbox": [25.6, 35.8, 44.8, 42.2],
        "description": "Anatolia and Eastern Mediterranean country bbox.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "TR",
        "featured": False,
    },
    {
        "id": "united-states",
        "label": "United States",
        "region_name": "United States GBIF bbox",
        "bbox": [-125.0, 24.0, -66.5, 49.5],
        "description": "Contiguous US bbox; keep max records moderate.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "US",
        "featured": False,
    },
    {
        "id": "canada",
        "label": "Canada",
        "region_name": "Canada GBIF bbox",
        "bbox": [-141.0, 41.7, -52.6, 83.1],
        "description": "Large country bbox for northern species tests.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "CA",
        "featured": False,
    },
    {
        "id": "brazil",
        "label": "Brazil",
        "region_name": "Brazil GBIF bbox",
        "bbox": [-74.0, -34.0, -34.8, 5.3],
        "description": "Large tropical country bbox; use focused taxa.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "BR",
        "featured": False,
    },
    {
        "id": "south-africa",
        "label": "South Africa",
        "region_name": "South Africa GBIF bbox",
        "bbox": [16.4, -35.0, 32.9, -22.0],
        "description": "Country bbox for southern Africa biodiversity checks.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "ZA",
        "featured": False,
    },
    {
        "id": "australia",
        "label": "Australia",
        "region_name": "Australia GBIF bbox",
        "bbox": [112.0, -44.0, 154.0, -10.0],
        "description": "Continental country bbox; use moderate max records.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "AU",
        "featured": False,
    },
    {
        "id": "japan",
        "label": "Japan",
        "region_name": "Japan GBIF bbox",
        "bbox": [129.0, 30.0, 146.0, 46.0],
        "description": "Island-country bbox for East Asia workflows.",
        "type": "country",
        "group": "Saved countries",
        "country_code": "JP",
        "featured": False,
    },
]


POPULAR_TAXA: list[dict[str, Any]] = [
    {
        "usageKey": 1651430,
        "scientificName": "Aedes albopictus",
        "canonicalName": "Aedes albopictus",
        "rank": "SPECIES",
        "status": "ACCEPTED",
        "kingdom": "Animalia",
        "family": "Culicidae",
        "confidence": 100,
        "source": "curated_demo",
    },
    {
        "usageKey": 2878688,
        "scientificName": "Quercus robur L.",
        "canonicalName": "Quercus robur",
        "rank": "SPECIES",
        "status": "ACCEPTED",
        "kingdom": "Plantae",
        "family": "Fagaceae",
        "confidence": 100,
        "source": "curated_demo",
    },
    {
        "usageKey": 2435261,
        "scientificName": "Lynx pardinus (Temminck, 1827)",
        "canonicalName": "Lynx pardinus",
        "rank": "SPECIES",
        "status": "ACCEPTED",
        "kingdom": "Animalia",
        "family": "Felidae",
        "confidence": 100,
        "source": "curated_demo",
    },
    {
        "usageKey": 1341976,
        "scientificName": "Apis mellifera Linnaeus, 1758",
        "canonicalName": "Apis mellifera",
        "rank": "SPECIES",
        "status": "ACCEPTED",
        "kingdom": "Animalia",
        "family": "Apidae",
        "confidence": 100,
        "source": "curated_demo",
    },
    {
        "usageKey": 5231190,
        "scientificName": "Passer domesticus (Linnaeus, 1758)",
        "canonicalName": "Passer domesticus",
        "rank": "SPECIES",
        "status": "ACCEPTED",
        "kingdom": "Animalia",
        "family": "Passeridae",
        "confidence": 100,
        "source": "curated_demo",
    },
]
